services:
  px4_sim:
    container_name: px4_sim_ros
    network_mode: host
    image: px4_sim_ros

    privileged: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    stop_signal: SIGINT
    # stop_grace_period: 30m
    runtime: nvidia
    env_file:
      - env
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:rwx
      - /sys:/sys
      - /etc/udev:/etc/udev
      - /run/udev:/run/udev
      - /run/dbus/:/run/dbus
      - /dev:/dev
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ./worlds:/app/PX4-Autopilot/Tools/simulation/gz/worlds
      - ./models:/app/PX4-Autopilot/Tools/simulation/gz/models
      - ./airframes:/app/PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/airframes

# need for Nvidia gpu:
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

    devices:
      - "/dev/dri/:/dev/dri/"
      - /dev/snd:/dev/snd

    group_add:
      - video
      - dialout
      - 1001
